# Generated by Django 3.0.3 on 2020-04-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_message_messagenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Control',
        ),
    ]
