# Generated by Django 3.0.3 on 2020-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.BinaryField()),
                ('groupName', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
