# Generated by Django 3.0.3 on 2020-04-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200412_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='poster',
            new_name='sender',
        ),
    ]
